// Theme constants + the hardcoded product catalog (edited by hand — the
// catalog deliberately does NOT live in Firestore; only interactions do).
// Shared by App.jsx (storefront) and Results.jsx (private review view).

export const SERIF = "'EB Garamond', Georgia, 'Times New Roman', serif";
export const TITLE = "'Jost', system-ui, sans-serif";
export const BG = "#faf7f1";
export const INK = "#1c1b19";
export const MUTE = "#8b857d";
export const LINE = "rgba(0,0,0,0.10)";
export const TILE_BG = "#efece5";
export const GREEN = "#3f7d4e";
export const BTN = { background: "#eae4d8", color: INK, border: "1px solid rgba(0,0,0,0.14)", fontFamily: SERIF };
export const SMBTN = { ...BTN, fontSize: 13, borderRadius: 6 };

export const FONTS_IMPORT =
  "@import url('https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400;0,500;0,600;1,400&family=Jost:wght@400;500;600&display=swap');";

export const CATS = ["All", "Witchcraft", "Decks", "Books", "Games", "Dolls", "Home", "Apparel", "Curios"];

export const IMG = {
  ants: "/images/ants.jpg",
  blocks: "/images/blocks.jpg",
  quilt: "/images/quilt.jpg",
  hat: "/images/hat.jpg",
  pillow: "/images/pillow.jpg",
  doll: "/images/doll.jpg",
  tea: "/images/tea.jpg",
  spires: "/images/spires.jpg",
  waiting: "/images/waiting.jpg",
  meaning: "/images/meaning.jpg",
  books: "/images/books.jpg",
  qroom: "/images/qroom.jpg",
  tee: "/images/tee.jpg",
  cube: "/images/cube.jpg",
  memory: "/images/memory.jpg",
  tote: "/images/tote.jpg",
  mythical: "/images/mythical.jpg",
  cb_cover: "/images/cb_cover.jpg",
  cb_life: "/images/cb_life.jpg",
  cb_meeting: "/images/cb_meeting.jpg",
  cb_paper: "/images/cb_paper.jpg",
  cb_dentist: "/images/cb_dentist.jpg",
  cb_kitchen: "/images/cb_kitchen.jpg",
  cb_laundry: "/images/cb_laundry.jpg",
  flow_box: "/images/flow_box.jpg",
  flow_cards: "/images/flow_cards.jpg",
  apoth_box: "/images/apoth_box.jpg",
  apoth_cards: "/images/apoth_cards.jpg",
  both_boxes: "/images/both_boxes.jpg",
  mineral_cards: "/images/mineral_cards.jpg",
  rituals: "/images/rituals.jpg",
  zine: "/images/zine.jpg",
  cap: "/images/cap.jpg",
  eyehat: "/images/eyehat.jpg",
  eyehat_colors: "/images/eyehat_colors.jpg",
  eyehat_model: "/images/eyehat_model.jpg",
  miracles: "/images/miracles.jpg",
  env_open: "/images/env_open.jpg",
  env_tent: "/images/env_tent.jpg",
  env_flat: "/images/env_flat.jpg",
  notice1: "/images/notice1.jpg",
  notice2: "/images/notice2.jpg",
  notice3: "/images/notice3.jpg",
  notice4: "/images/notice4.jpg",
  ostrich: "/images/ostrich.jpg",
  snake: "/images/snake.jpg",
  snake_pkg: "/images/snake_pkg.jpg",
  purse: "/images/purse.jpg",
  purse2: "/images/purse2.jpg",
  brooch1: "/images/brooch1.jpg",
  brooch2: "/images/brooch2.jpg",
  symbols: "/images/symbols.jpg",
  doll2: "/images/doll2.jpg",
  comic: "/images/comic.jpg",
  arms1: "/images/arms1.jpg",
  arms2: "/images/arms2.jpg",
  tok1: "/images/tok1.jpg",
  tok2: "/images/tok2.jpg",
  toy1: "/images/toy1.jpg",
  toy2: "/images/toy2.jpg",
  gal1: "/images/gal1.jpg",
  gal2: "/images/gal2.jpg",
  wcoins: "/images/wcoins.jpg",
  castles: "/images/castles.jpg",
  dogoracle: "/images/dogoracle.jpg",
  humanfrag: "/images/humanfrag.jpg",
  zodiac: "/images/zodiac.jpg",
};

export const seed = [
  { id: 1, cat: "Curios", imgs: [IMG.ants], title: "Little Box of Ants", retail: 18, cost: 9, goal: 100,
    desc: "A little box of ants. Not for eating. A small, unsettling gift for someone with a sense of humor." },
  { id: 2, cat: "Home", imgs: [IMG.blocks], title: "Illustrated Blocks", retail: 54, cost: 28, goal: 100,
    desc: "A stacked set of illustrated wooden blocks, each face a small melancholic scene." },
  { id: 3, cat: "Home", imgs: [IMG.quilt, IMG.qroom], title: "Folk Symbol Quilt", retail: 120, cost: 62, goal: 100,
    desc: "A quilted cotton throw scattered with folk symbols — eyes, keys, ghosts, candles, and stars." },
  { id: 4, cat: "Apparel", imgs: [IMG.hat], title: "Strawberry Bucket Hat", retail: 42, cost: 21, goal: 100,
    desc: "A cream cotton bucket hat with hand-embroidered strawberries and daisies." },
  { id: 5, cat: "Home", imgs: [IMG.pillow], title: "Embroidered Pillow", retail: 38, cost: 19, goal: 100,
    desc: "A plush embroidered pillow — strawberries and daisies stitched in soft wool." },
  { id: 6, cat: "Dolls", imgs: [IMG.doll, IMG.doll2], title: "Velvet Baby Doll", retail: 48, cost: 24, goal: 100,
    desc: "A sleeping velvet doll with a porcelain face and pearl buttons. Strange and a little tender." },
  { id: 7, cat: "Witchcraft", imgs: [IMG.tea], title: "Secretly a Witch Tea", retail: 24, cost: 12, goal: 100,
    desc: "Four illustrated tea tins — The Moon Said Nothing, A Room Full of Signs, Evening Spell, and Fortune Mint." },
  { id: 8, cat: "Home", imgs: [IMG.spires], title: "Spires", retail: 36, cost: 18, goal: 100,
    desc: "Decorations for an obsolete world — a boxed set of tiny wooden spires, doors, and trees." },
  { id: 9, cat: "Games", imgs: [IMG.waiting], title: "The Waiting Game", retail: 28, cost: 14, goal: 100,
    desc: "The patience-packed tabletop game. Sit. Wait. Collect. Win. Includes a sugar-packet holder and 50 handmade sugar packets." },
  { id: 10, cat: "Games", imgs: [IMG.meaning], title: "Too Much Meaning", retail: 34, cost: 17, goal: 100,
    desc: "A game about one sleepless night. Move through the night, draw dream cards, find your way to morning. There is no single answer." },
  { id: 11, cat: "Books", imgs: [IMG.books], title: "Little Books", retail: 14, cost: 7, goal: 100,
    desc: "A passport-format series of pocket guides — each title its own little book.",
    titlePrefix: "Little Book of ", variantLabel: "Choose a title",
    variants: ["Miracles", "Manifestation", "Luck", "Superstitions", "Plant Magick", "Wishes"] },
  { id: 12, cat: "Apparel", imgs: [IMG.tee], title: "People Watching Club Tee", retail: 32, cost: 16, goal: 100,
    desc: "A cream cotton tee with the People Watching Club seal — for dedicated observers." },
  { id: 13, cat: "Home", imgs: [IMG.cube], title: "Ruffle Cube Pillow", retail: 34, cost: 17, goal: 100,
    desc: "A soft cube pillow trimmed in navy ruffles. Equal parts toy and decor." },
  { id: 14, cat: "Books", imgs: [IMG.memory], title: "Memory Passport", retail: 20, cost: 10, goal: 100,
    desc: "A passport for your memories — collect illustrated stamps of the moments worth keeping." },
  { id: 15, cat: "Apparel", imgs: [IMG.tote], title: "People Watching Club Tote", retail: 24, cost: 12, goal: 100,
    desc: "A heavyweight canvas tote stamped with the People Watching Club seal." },
  { id: 16, cat: "Decks", imgs: [IMG.mythical], title: "Mythical Creatures", retail: 28, cost: 14, goal: 100,
    desc: "A reference deck of mythical creatures — lore, traits, and magical correspondences for each." },
  { id: 17, cat: "Books", imgs: [IMG.cb_cover, IMG.cb_life, IMG.cb_meeting, IMG.cb_paper, IMG.cb_dentist, IMG.cb_kitchen, IMG.cb_laundry], title: "Adult(ing) Coloring Book", retail: 18, cost: 9, goal: 100,
    desc: "A coloring book about all the best parts of being an adult — traffic, dishes, dentists, and meetings that could have been emails." },
  { id: 18, cat: "Decks", stage: "made", imgs: [IMG.flow_box, IMG.flow_cards], title: "The Magic of Flowers", retail: 28, cost: 14, goal: 100,
    desc: "A reference deck of flowers — each card a botanical illustration with its practical uses and magical correspondences." },
  { id: 19, cat: "Decks", stage: "made", imgs: [IMG.apoth_box, IMG.apoth_cards], title: "Apothecary Reference Cards", retail: 28, cost: 14, goal: 100,
    desc: "A reference deck of herbs and remedies — each card a botanical with its practical and magical uses." },
  { id: 20, cat: "Decks", stage: "made", imgs: [IMG.mineral_cards, IMG.both_boxes], title: "Mineralogy Reference Cards", retail: 28, cost: 14, goal: 100,
    desc: "A reference deck of minerals and crystals — illustrated specimens with their metaphysical properties." },
  { id: 21, cat: "Decks", stage: "production", imgs: [IMG.rituals], title: "Magic Rituals", retail: 32, cost: 16, goal: 100,
    desc: "A deck of magic rituals for modern life — ancient wisdom, one ritual per card. Currently being printed." },
  { id: 22, cat: "Books", imgs: [IMG.zine, IMG.comic], title: "Talking to Myself", retail: 16, cost: 8, goal: 100,
    desc: "An illustrated zine — small interior scenes and a quiet conversation with oneself." },
  { id: 23, cat: "Apparel", imgs: [IMG.cap], title: "People Watching Club Cap", retail: 28, cost: 14, goal: 100,
    desc: "A washed-green embroidered cap with the People Watching Club mark in cream Garamond small caps." },
  { id: 24, cat: "Apparel", imgs: [IMG.eyehat, IMG.eyehat_colors, IMG.eyehat_model], title: "My Eye Is Up Here", retail: 28, cost: 14, goal: 100,
    variantLabel: "Choose a colour",
    variants: ["Rust / Navy", "Khaki / Forest", "Navy / Bone", "Olive / Khaki", "Charcoal / Black", "Slate Blue / Stone"],
    desc: "A washed cotton dad cap with an embroidered eye and \"my eye is up here.\" Two-tone, in six colourways." },
  { id: 25, cat: "Books", imgs: [IMG.miracles, IMG.notice1, IMG.notice2, IMG.notice3, IMG.notice4], title: "Little Book of Miracles", retail: 14, cost: 7, goal: 100,
    desc: "A pocket book of small miracles — bound in black with gold foil. One little book in the series." },
  { id: 26, cat: "Curios", imgs: [IMG.env_open, IMG.env_tent, IMG.env_flat], title: "Stitched Envelope", retail: 24, cost: 12, goal: 100,
    desc: "A hand-stitched cotton envelope edged in green running stitch — folds flat or stands open." },
  { id: 27, cat: "Apparel", imgs: [IMG.ostrich], title: "Ostrich Logic", retail: 28, cost: 14, goal: 100,
    desc: "A washed-green dad cap embroidered with \"ostrich logic\" in cream serif." },
  { id: 28, cat: "Home", imgs: [IMG.snake, IMG.snake_pkg], title: "Snake Embroidered Pillow", retail: 38, cost: 19, goal: 100,
    desc: "A plush embroidered snake pillow — a starry green serpent on natural cotton." },
  { id: 29, cat: "Curios", imgs: [IMG.purse, IMG.purse2], title: "Portrait Coin Purse", retail: 32, cost: 16, goal: 100,
    desc: "A clasp coin purse in mauve cotton with a hand-embroidered portrait and lace collar." },
  { id: 30, cat: "Curios", imgs: [IMG.brooch1, IMG.brooch2], title: "Portrait Brooch", retail: 22, cost: 11, goal: 100,
    desc: "A small stuffed-cotton brooch — a hand-drawn face with a ruffled collar." },
  { id: 31, cat: "Curios", imgs: [IMG.symbols], title: "Symbol Stones", retail: 36, cost: 18, goal: 100,
    desc: "A set of small embroidered cotton stones, each marked with its own little symbol." },
  { id: 32, cat: "Curios", imgs: [IMG.arms1, IMG.arms2], title: "Holding Hands", retail: 44, cost: 22, goal: 100,
    desc: "A soft sculpture — a ring of stuffed cotton arms, hand in hand." },
  { id: 33, cat: "Curios", imgs: [IMG.tok1, IMG.tok2], title: "Wooden Tokens", retail: 30, cost: 15, goal: 100,
    desc: "A linen pouch of little engraved wooden tokens — faces, symbols, and signs to draw from." },
  { id: 34, cat: "Curios", imgs: [IMG.toy1, IMG.toy2], title: "Wooden Toys", retail: 34, cost: 17, goal: 100,
    desc: "Small engraved wooden curios — a carriage and a swan, each with a hidden face." },
  { id: 35, cat: "Curios", imgs: [IMG.gal1, IMG.gal2], title: "Tiny Gallery of People You Don't Know", retail: 24, cost: 12, goal: 100,
    desc: "A pack of miniature gilt-framed portraits of perfect strangers." },
  { id: 36, cat: "Curios", imgs: [IMG.wcoins], title: "Women Coins", retail: 22, cost: 11, goal: 100,
    desc: "A set of cast metal coins struck with the faces of women worth remembering." },
  { id: 37, cat: "Decks", imgs: [IMG.castles], title: "Castles", retail: 26, cost: 13, goal: 100,
    desc: "A deck of castles — watercolour fortresses, keeps, and follies, one to a card." },
  { id: 38, cat: "Decks", imgs: [IMG.dogoracle], title: "Dog Breeds Oracle", retail: 30, cost: 15, goal: 100,
    desc: "An oracle deck of dog breeds — pull a pup for the day's guidance." },
  { id: 39, cat: "Decks", imgs: [IMG.humanfrag], title: "Human Fragments", retail: 12, cost: 6, goal: 100,
    desc: "Collectible body-part cards — five random fragments per pack. Look for rare & special editions." },
  { id: 40, cat: "Witchcraft", imgs: [IMG.zodiac], title: "Zodiac Supplements", retail: 32, cost: 16, goal: 100,
    desc: "Daily supplements formulated for your sun sign. Structure for Capricorn, hydration for Aquarius. 60 capsules · mind & matter." },
];

export const targetOf = (it) => it.cost * it.goal;
export const pctOf = (it) => { const t = targetOf(it); return t > 0 ? Math.min(100, (it.raised / t) * 100) : 0; };
