name: Miracles
options:
  bundleIdPrefix: com.sageryza
  deploymentTarget:
    iOS: "16.0"
packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    from: "11.0.0"
targets:
  Miracles:
    type: application
    platform: iOS
    sources:
      - Miracles
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.sageryza.miracles
        GENERATE_INFOPLIST_FILE: YES
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        CODE_SIGN_STYLE: Automatic
        INFOPLIST_KEY_CFBundleDisplayName: Miracles
        INFOPLIST_KEY_ITSAppUsesNonExemptEncryption: NO
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_VERSION: "5.0"
    dependencies:
      - package: Firebase
        product: FirebaseCore
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseFunctions
      - package: Firebase
        product: FirebaseFirestore
